# Generated by Django 2.0.1 on 2018-01-17 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hauz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='maintenance',
            new_name='maintenance_id',
        ),
    ]
