# Generated by Django 2.0.1 on 2018-01-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hauz', '0002_auto_20180117_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='occupancy',
            field=models.BooleanField(default=False),
        ),
    ]
