ns  # Generated by Django 2.0.1 on 2018-01-17 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hauz', '0003_house_occupancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='property_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='property_expense', to='Hauz.Property'),
        ),
    ]
