# Generated by Django 2.0.1 on 2018-01-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hauz', '0005_expense_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
