# Generated by Django 2.0.1 on 2018-01-18 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hauz', '0006_property_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_property', to='Hauz.Property_Group'),
        ),
    ]
