# Generated by Django 2.0.1 on 2018-01-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hauz', '0008_property_group_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='property',
            table='property',
        ),
    ]
