# Generated by Django 2.0.1 on 2018-01-18 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hauz', '0010_auto_20180118_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_types', to='Hauz.Property_Type'),
        ),
    ]
