# Generated by Django 2.0.1 on 2018-01-19 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hauz', '0012_auto_20180118_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_houses', to='Hauz.Property'),
        ),
    ]
