# Generated by Django 2.0.1 on 2018-01-19 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hauz', '0014_auto_20180119_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='tenant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_tenant', to='Hauz.Tenant'),
        ),
    ]
