# Generated by Django 2.0.1 on 2018-01-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hauz', '0015_auto_20180119_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='maintenance_id',
            new_name='maintenances',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='property_id',
            new_name='property_types',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='tenant_id',
            new_name='tenants',
        ),
        migrations.RemoveField(
            model_name='house',
            name='amenity_id',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(to='Hauz.Amenity'),
        ),
    ]
