# Generated by Django 2.0.1 on 2018-01-22 12:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Hauz', '0018_auto_20180120_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='house',
            name='tenants',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tenant',
        ),
        migrations.AddField(
            model_name='house',
            name='account_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='original_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='tenant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
