# Generated by Django 2.0.1 on 2018-01-22 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hauz', '0019_auto_20180122_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('original_id', models.PositiveIntegerField()),
                ('account_no', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_tenant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant',
            },
        ),
        migrations.RemoveField(
            model_name='house',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='house',
            name='original_id',
        ),
        migrations.RemoveField(
            model_name='house',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='house',
            name='tenant',
        ),
        migrations.AddField(
            model_name='house',
            name='tenants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_tenant', to='Hauz.Tenant'),
        ),
    ]
