# Generated by Django 2.0.1 on 2018-01-22 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hauz', '0020_auto_20180122_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='tenants',
        ),
        migrations.AddField(
            model_name='tenant',
            name='house_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_tenant', to='Hauz.House'),
        ),
    ]
