# Generated by Django 2.0.1 on 2018-01-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hauz', '0022_expense_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.CharField(blank=True, choices=[('Jan', 'january'), ('Feb', 'february'), ('Mar', 'march'), ('Apr', 'april'), ('May', 'may'), ('Jun', 'june'), ('July', 'july'), ('Aug', 'august'), ('Sep', 'september'), ('Oct', 'october'), ('Nov', 'november'), ('Dec', 'december')], default='jan', max_length=30),
        ),
    ]
