# Generated by Django 2.0.1 on 2018-01-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hauz', '0023_auto_20180122_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='maintenances',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='property_id',
        ),
        migrations.AddField(
            model_name='property',
            name='cleaning',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='gabbage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='security',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
