# Generated by Django 2.0.1 on 2018-01-24 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hauz', '0025_auto_20180124_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='house',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='house',
            name='occupancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='property_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_payment', to='Hauz.Property'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
